spring:
  datasource:
    url: jdbc:mysql://localhost:3306/digital_support_portal
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  sendgrid:
    api-key:
server:
  port: 10000


jwt:
  secret: 8b11203cec8323805a943724bd2b75ef4bf7ba0412d233880d7ca0cd61a1ee7b

azure:
  activedirectory:
    tenant-id: dfsdf
    client-secret: sfdsfsd
    client-id: sfdsd

sharepoint:
  site-id: sdfsdfsd
  drive-id: sdfdsfds